# Generated by Django 5.2.7 on 2025-11-17 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único del atributo.', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o notas internas sobre esta opción.', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Marcar si esta opción está disponible para nuevos registros.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
            },
        ),
        migrations.CreateModel(
            name='CueroCabelludo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único del atributo.', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o notas internas sobre esta opción.', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Marcar si esta opción está disponible para nuevos registros.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cueros Cabelludos',
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único del atributo.', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o notas internas sobre esta opción.', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Marcar si esta opción está disponible para nuevos registros.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Estados Generales',
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrosorCabello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único del atributo.', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o notas internas sobre esta opción.', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Marcar si esta opción está disponible para nuevos registros.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Grosores de Cabello',
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PorosidadCabello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único del atributo.', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o notas internas sobre esta opción.', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Marcar si esta opción está disponible para nuevos registros.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Porosidades de Cabello',
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCabello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único del atributo.', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o notas internas sobre esta opción.', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Marcar si esta opción está disponible para nuevos registros.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Cabello',
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único del atributo.', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o notas internas sobre esta opción.', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Marcar si esta opción está disponible para nuevos registros.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('duracion_estimada', models.IntegerField(blank=True, null=True, verbose_name='Duración Estimada (en minutos)')),
                ('precio_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Base')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.categoriaservicio', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='ReglaDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.IntegerField(default=0, help_text='Reglas con número más alto se evalúan primero')),
                ('mensaje_resultado', models.TextField(help_text='El mensaje que verá el cliente si esta regla coincide')),
                ('accion_resultado', models.CharField(help_text='Código de acción que el frontend usará para decidir qué mostrar', max_length=50)),
                ('cuero_cabelludo', models.ForeignKey(blank=True, help_text="Dejar vacío para 'Cualquier cuero cabelludo'", null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.cuerocabelludo')),
                ('estado_general', models.ForeignKey(blank=True, help_text="Dejar vacío para 'Cualquier estado'", null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.estadogeneral')),
                ('grosor_cabello', models.ForeignKey(blank=True, help_text="Dejar vacío para 'Cualquier grosor'", null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.grosorcabello')),
                ('porosidad_cabello', models.ForeignKey(blank=True, help_text="Dejar vacío para 'Cualquier porosidad'", null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.porosidadcabello')),
                ('tipo_cabello', models.ForeignKey(blank=True, help_text="Dejar vacío para 'Cualquier tipo'", null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.tipocabello')),
            ],
            options={
                'ordering': ['-prioridad'],
            },
        ),
    ]
