# Generated by Django 5.2.7 on 2025-11-25 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_categoriaservicio_puntaje_ph_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo_turnos', models.IntegerField(default=30, help_text='Minutos de cada bloque en la grilla visual')),
                ('max_dias_anticipacion', models.IntegerField(default=60, help_text='Cuanto tiempo antes se puede reservar')),
                ('monto_sena', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('tiempo_limite_pago_sena', models.IntegerField(default=24, help_text='Horas para pagar antes de cancelar')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración',
            },
        ),
        migrations.CreateModel(
            name='HorarioLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Horario Laboral',
                'verbose_name_plural': 'Horarios Laborales',
                'ordering': ['dia'],
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='permite_simultaneidad',
            field=models.BooleanField(default=False, help_text='Si es True, Yani puede atender a otra persona durante el reposo.'),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin_calculada', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Seña'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('realizado', 'Realizado / Finalizado'), ('ausente', 'Ausente (No vino)')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_turnos', to='usuarios.cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.servicio')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
                'unique_together': {('fecha', 'hora_inicio', 'cliente')},
            },
        ),
    ]
