# Generated by Django 5.2.7 on 2025-12-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_configuracion_horariolaboral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('solicitado', 'Solicitado (Requiere Análisis)'), ('esperando_sena', 'Aprobado (Esperando Seña)'), ('confirmado', 'Confirmado (Seña OK)'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado / Rechazado'), ('ausente', 'Ausente (No vino)')], default='solicitado', max_length=20),
        ),
    ]
