# Generated by Django 5.2.7 on 2025-12-03 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_turno_estado'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaCuidados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('completado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ReglaCuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RESTRICCION', 'Restricción (Lo que NO debes hacer)'), ('HABITO', 'Hábito (Lo que DEBES hacer)')], max_length=20)),
                ('descripcion', models.CharField(help_text='Ej: No mojar el cabello', max_length=255)),
                ('dias_duracion', models.IntegerField(default=0, help_text='Duración de la regla en días (0 = puntual/un solo día)')),
                ('frecuencia_dias', models.IntegerField(blank=True, help_text='Cada cuántos días repetir (solo para hábitos)', null=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_post_servicio', to='gestion.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(help_text='Descripción general de la rutina.')),
                ('activo', models.BooleanField(default=True)),
                ('tipo_cabello_ideal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.tipocabello')),
            ],
        ),
        migrations.CreateModel(
            name='PasoRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='gestion.rutina')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='regladiagnostico',
            name='rutina_sugerida',
            field=models.ForeignKey(blank=True, help_text='La rutina que se asignará automáticamente al cliente.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.rutina'),
        ),
    ]
