# Generated by Django 5.2.7 on 2025-12-05 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_agendacuidados_reglacuidado_rutina_pasorutina_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('informativa', 'Informativa'), ('alerta', 'Alerta'), ('recordatorio', 'Recordatorio')], default='informativa', max_length=50)),
                ('canal', models.CharField(choices=[('app', 'Aplicación (In-App)'), ('email', 'Correo Electrónico'), ('whatsapp', 'WhatsApp')], default='app', max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('leido', 'Leído'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('origen_entidad', models.CharField(blank=True, help_text="Ej: 'Turno', 'Promocion'", max_length=50, null=True)),
                ('origen_id', models.IntegerField(blank=True, help_text='ID de la entidad origen', null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
