# Generated by Django 5.2.7 on 2025-12-05 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_notificacion'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasorutina',
            options={'ordering': ['orden'], 'verbose_name': 'Paso de Rutina', 'verbose_name_plural': 'Pasos de Rutina'},
        ),
        migrations.RenameField(
            model_name='pasorutina',
            old_name='rutina',
            new_name='plantilla',
        ),
        migrations.RemoveField(
            model_name='pasorutina',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='tipo_cabello_ideal',
        ),
        migrations.AddField(
            model_name='pasorutina',
            name='frecuencia',
            field=models.CharField(default='Diaria', help_text='Ej: Diaria, Semanal', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rutina',
            name='clientes_asignados',
            field=models.ManyToManyField(blank=True, help_text='Clientes que tienen esta rutina asignada', related_name='rutinas_asignadas', to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='creada_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='rutinas_creadas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rutina',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('obsoleta', 'Obsoleta')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='rutina',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-04 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rutina',
            name='fecha_obsoleta',
            field=models.DateTimeField(blank=True, help_text='Fecha en que la rutina fue marcada como obsoleta', null=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='objetivo',
            field=models.CharField(default='Cuidado del cabello', help_text='Ej: Hidratación profunda', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rutina',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pasorutina',
            name='orden',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='RutinaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('objetivo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('version_asignada', models.PositiveIntegerField(help_text='La versión de la rutina original cuando se copió')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('desactualizada', 'Desactualizada'), ('obsoleta_original', 'Original Obsoleta'), ('completada', 'Completada')], default='activa', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('descargar_notificacion', models.BooleanField(default=False, help_text='¿Se le notificó al cliente sobre descarga/actualización?')),
                ('fecha_ultima_notificacion', models.DateTimeField(blank=True, help_text='Cuándo se le notificó de una actualización disponible', null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_cliente', to='usuarios.cliente')),
                ('rutina_original', models.ForeignKey(blank=True, help_text='Referencia a la rutina original (puede ser NULL si fue eliminada)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copias_cliente', to='gestion.rutina')),
            ],
            options={
                'verbose_name': 'Rutina del Cliente',
                'verbose_name_plural': 'Rutinas del Cliente',
                'ordering': ['-fecha_asignacion'],
                'unique_together': {('cliente', 'rutina_original')},
            },
        ),
        migrations.CreateModel(
            name='PasoRutinaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('frecuencia', models.CharField(help_text='Ej: Diaria, Semanal', max_length=100)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('rutina_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='gestion.rutinacliente')),
            ],
            options={
                'verbose_name': 'Paso de Rutina del Cliente',
                'verbose_name_plural': 'Pasos de Rutina del Cliente',
                'ordering': ['orden'],
            },
        ),
    ]
