# Generated by Django 5.2.7 on 2025-12-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_pasorutina_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasorutina',
            name='titulo',
            field=models.CharField(default='Paso', max_length=200),
            preserve_default=False,
        ),
    ]
