# Generated by Django 5.2.7 on 2025-12-05 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_pasorutina_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='impacto_estado',
            field=models.ForeignKey(blank=True, help_text='Estado general en el que quedará el cabello (ej: Seco, Dañado).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.estadogeneral'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='impacto_porosidad',
            field=models.ForeignKey(blank=True, help_text='Nivel de porosidad que tendrá el cabello después del servicio.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.porosidadcabello'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='rutina_recomendada',
            field=models.ForeignKey(blank=True, help_text='Rutina que se asignará automáticamente al finalizar este servicio.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.rutina'),
        ),
    ]
