# Generated by Django 5.2.7 on 2025-12-05 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_servicio_impacto_estado_servicio_impacto_porosidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglacuidado',
            name='rutina',
            field=models.ForeignKey(blank=True, help_text='Rutina específica recomendada para esta regla.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_cuidado', to='gestion.rutina'),
        ),
    ]
