# Generated by Django 5.2.7 on 2025-12-05 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_reglacuidado_rutina'),
        ('usuarios', '0002_cliente_rutinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='max_reprogramaciones',
            field=models.IntegerField(default=2, help_text='Cuántas veces se puede cambiar el turno sin perder la seña'),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='cambios_realizados',
            field=models.PositiveIntegerField(default=0, help_text='Contador de reprogramaciones hechas por el cliente'),
        ),
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_deseada_inicio', models.DateField()),
                ('fecha_deseada_fin', models.DateField()),
                ('hora_rango_inicio', models.TimeField(default='08:00')),
                ('hora_rango_fin', models.TimeField(default='20:00')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notificado', models.BooleanField(default=False, help_text='Si ya se le avisó de un hueco disponible')),
                ('activa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esperas', to='usuarios.cliente')),
                ('servicio_interes', models.ForeignKey(help_text='Servicio que la clienta quiere realizarse', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.servicio')),
            ],
            options={
                'verbose_name': 'Lista de Espera',
                'verbose_name_plural': 'Listas de Espera',
                'ordering': ['fecha_registro'],
            },
        ),
    ]
