# Generated by Django 5.2.7 on 2025-12-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_configuracion_max_reprogramaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='horas_limite_cancelacion',
            field=models.IntegerField(default=48, help_text='Horas antes del turno en las que se bloquea la cancelación automática por parte del cliente.'),
        ),
    ]
