# Generated by Django 5.2.7 on 2025-12-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_configuracion_horas_limite_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='cambios_realizados',
            field=models.IntegerField(default=0, help_text='Contador de cuántas veces se ha reprogramado este turno'),
        ),
    ]
