# Generated by Django 5.1.12 on 2025-12-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_turno_cambios_realizados'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='datos_extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('informativa', 'Informativa'), ('alerta', 'Alerta'), ('recordatorio', 'Recordatorio'), ('ADELANTO', 'Oferta de Adelanto de Turno')], default='informativa', max_length=50),
        ),
    ]
