# Generated by Django 5.1.12 on 2025-12-14 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_equipamiento_producto'),
        ('usuarios', '0002_cliente_rutinas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasorutinacliente',
            name='rutina_cliente',
        ),
        migrations.AlterUniqueTogether(
            name='rutinacliente',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rutina',
            name='archivo',
            field=models.FileField(default='1', help_text='Sube el diseño exportado de Canva o Word.', upload_to='rutinas_pdfs/', verbose_name='Documento de Rutina (PDF/Img)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rutinacliente',
            name='archivo',
            field=models.FileField(default='', upload_to='rutinas_clientes/', verbose_name='Archivo Asignado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rutina',
            name='clientes_asignados',
            field=models.ManyToManyField(blank=True, related_name='rutinas_asignadas', to='usuarios.cliente'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Notas internas'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='fecha_obsoleta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rutinacliente',
            name='descargar_notificacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rutinacliente',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='rutinacliente',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('desactualizada', 'Desactualizada'), ('obsoleta_original', 'Original Obsoleta'), ('archivada', 'Archivada')], default='activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='rutinacliente',
            name='fecha_ultima_notificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rutinacliente',
            name='rutina_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copias_cliente', to='gestion.rutina'),
        ),
        migrations.AlterField(
            model_name='rutinacliente',
            name='version_asignada',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='PasoRutina',
        ),
        migrations.DeleteModel(
            name='PasoRutinaCliente',
        ),
    ]
