# Generated by Django 5.2.7 on 2025-12-14 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_remove_pasorutinacliente_rutina_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariolaboral',
            options={'ordering': ['dia_semana', 'hora_inicio'], 'verbose_name': 'Horario Laboral', 'verbose_name_plural': 'Horarios Laborales'},
        ),
        migrations.RemoveField(
            model_name='horariolaboral',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='horariolaboral',
            name='cambios_realizados',
        ),
        migrations.RemoveField(
            model_name='horariolaboral',
            name='dia',
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=0),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='horas_limite_cancelacion',
            field=models.IntegerField(default=48, help_text='Horas antes del turno donde YA NO se puede cancelar y recuperar la seña.'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='intervalo_turnos',
            field=models.IntegerField(default=30, help_text='Minutos de cada bloque visual en la agenda'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='max_reprogramaciones',
            field=models.IntegerField(default=2, help_text='Máximo de cambios permitidos por cliente'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='monto_sena',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10, verbose_name='Monto de Seña'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='tiempo_limite_pago_sena',
            field=models.IntegerField(default=24, help_text='Horas para pagar la seña antes de cancelar automático'),
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('colorista', 'Colorista / Principal'), ('asistente', 'Asistente / Lavado'), ('administrador', 'Administrador')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('realiza_diagnostico', models.BooleanField(default=False)),
                ('realiza_lavado', models.BooleanField(default=True)),
                ('realiza_color', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('color_calendario', models.CharField(default='#E11D48', help_text='Color Hex para identificarlo en la agenda', max_length=7)),
                ('usuario', models.OneToOneField(blank=True, help_text='Vincular solo si esta persona necesita loguearse al sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_profesional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal / Staff',
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='BloqueoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('motivo', models.CharField(max_length=200)),
                ('bloquea_todo_el_dia', models.BooleanField(default=False)),
                ('personal', models.ForeignKey(blank=True, help_text='Si se deja vacío, aplica a TODO el salón (ej. Feriado Nacional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='gestion.personal')),
            ],
            options={
                'verbose_name': 'Bloqueo / Excepción de Agenda',
                'verbose_name_plural': 'Bloqueos de Agenda',
            },
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='gestion.personal'),
        ),
    ]
