# Generated by Django 5.2.7 on 2025-12-22 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_alter_horariolaboral_options_and_more'),
        ('usuarios', '0002_cliente_rutinas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendacuidados',
            options={'ordering': ['fecha'], 'verbose_name': 'Agenda de Cuidados', 'verbose_name_plural': 'Agendas de Cuidados'},
        ),
        migrations.AlterModelOptions(
            name='bloqueoagenda',
            options={'ordering': ['fecha_inicio'], 'verbose_name': 'Bloqueo / Excepción de Agenda', 'verbose_name_plural': 'Bloqueos de Agenda'},
        ),
        migrations.AlterModelOptions(
            name='categoriaservicio',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría de Servicio', 'verbose_name_plural': 'Categorías de Servicios'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='reglacuidado',
            options={'verbose_name': 'Regla de Cuidado', 'verbose_name_plural': 'Reglas de Cuidado'},
        ),
        migrations.AlterModelOptions(
            name='rutina',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Rutina', 'verbose_name_plural': 'Rutinas'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['fecha', 'hora_inicio'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.RemoveField(
            model_name='categoriaservicio',
            name='puntaje_base',
        ),
        migrations.AlterField(
            model_name='agendacuidados',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_cuidados', to='usuarios.cliente'),
        ),
        migrations.AlterField(
            model_name='categoriaservicio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categoriaservicio',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción de la categoría', null=True),
        ),
        migrations.AlterField(
            model_name='categoriaservicio',
            name='nombre',
            field=models.CharField(help_text='Nombre único del categoría.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='horas_limite_cancelacion',
            field=models.IntegerField(default=48, help_text='Horas antes del turno donde YA NO se puede cancelar.'),
        ),
        migrations.AlterField(
            model_name='listaespera',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listaespera',
            name='servicio_interes',
            field=models.ForeignKey(help_text='Servicio deseado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.servicio'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='origen_entidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='origen_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reglacuidado',
            name='dias_duracion',
            field=models.IntegerField(default=0, help_text='Duración de la regla en días (0 = puntual)'),
        ),
        migrations.AlterField(
            model_name='reglacuidado',
            name='frecuencia_dias',
            field=models.IntegerField(blank=True, help_text='Cada cuántos días repetir', null=True),
        ),
        migrations.AlterField(
            model_name='reglacuidado',
            name='rutina',
            field=models.ForeignKey(blank=True, help_text='Rutina específica recomendada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_cuidado', to='gestion.rutina'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='puntaje_base',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='turno',
            name='cambios_realizados',
            field=models.IntegerField(default=0, help_text='Contador de reprogramaciones'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('solicitado', 'Solicitado (Requiere Análisis)'), ('esperando_sena', 'Aprobado (Esperando Seña)'), ('confirmado', 'Confirmado (Seña OK)'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado / Rechazado'), ('ausente', 'Ausente (No vino)'), ('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso')], default='solicitado', max_length=20),
        ),
    ]
