# Generated by Django 5.2.7 on 2026-01-06 23:25

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_add_horariolaboral_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Equipamiento',
                'verbose_name_plural': 'Tipos de Equipamientos',
            },
        ),
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'En Mantenimiento'), ('FUERA_SERVICIO', 'Fuera de Servicio / Roto')], default='DISPONIBLE', max_length=20)),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación física dentro del salón', max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_adquisicion', models.DateField(default=timezone.now)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recursos', to='gestion.tipoequipamiento')),
            ],
            options={
                'verbose_name': 'Equipamiento',
                'verbose_name_plural': 'Equipamientos',
                'ordering': ['codigo'],
            },
        ),
    ]
