# Generated by Django 5.2.7 on 2026-01-08 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_equipamiento_tipoequipamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='equipamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.equipamiento'),
        ),
    ]
