# Generated by Django 5.2.7 on 2026-01-08 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_turno_equipamiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='servicio',
        ),
        migrations.AddField(
            model_name='turno',
            name='profesional',
            field=models.ForeignKey(default='1', limit_choices_to={'rol__in': ['PROFESIONAL', 'PERSONAL']}, on_delete=django.db.models.deletion.PROTECT, related_name='turnos_asignados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turno',
            name='cambios_realizados',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DetalleTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_historico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.servicio')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.turno')),
            ],
            options={
                'verbose_name': 'Detalle del Turno',
                'verbose_name_plural': 'Detalles del Turno',
                'unique_together': {('turno', 'servicio')},
            },
        ),
    ]
