# Generated by Django 5.2.7 on 2026-01-09 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_remove_turno_fecha_creacion_remove_turno_servicio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.TextField(help_text='Descripción de la mezcla química')),
                ('observaciones_proceso', models.TextField(blank=True, null=True)),
                ('resultado_post_servicio', models.TextField(blank=True, null=True)),
                ('foto_resultado', models.ImageField(blank=True, null=True, upload_to='fichas/resultados/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('detalle_turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica', to='gestion.detalleturno')),
                ('profesional_autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_redactadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha Técnica',
                'verbose_name_plural': 'Fichas Técnicas',
            },
        ),
    ]
