# Generated by Django 5.2.7 on 2026-01-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_fichatecnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='brillo_final',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='porosidad_final',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='servicio',
            name='plantilla_formula',
            field=models.TextField(blank=True, help_text='Estructura base: Base: __, Medios: __, Oxidante: __'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='formula',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='foto_resultado',
            field=models.ImageField(blank=True, null=True, upload_to='fichas_tecnicas/'),
        ),
    ]
