# Generated by Django 5.2.7 on 2026-01-09 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_fichatecnica_brillo_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichatecnica',
            name='brillo_final',
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='estado_general_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_registradas', to='gestion.estadogeneral', verbose_name='Estado General Post-Servicio'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='porosidad_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_registradas', to='gestion.porosidadcabello', verbose_name='Porosidad Post-Servicio'),
        ),
    ]
