# Generated by Django 5.2.7 on 2026-01-09 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_remove_fichatecnica_brillo_final_and_more'),
        ('usuarios', '0003_remove_cliente_historial_servicios_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoCapilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('fecha_diagnostico', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_capilares', to='usuarios.cliente')),
                ('cuero_cabelludo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.cuerocabelludo')),
                ('estado_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.estadogeneral')),
                ('grosor_cabello', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.grosorcabello')),
                ('porosidad_cabello', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.porosidadcabello')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos_realizados', to=settings.AUTH_USER_MODEL)),
                ('regla_diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos_generados', to='gestion.regladiagnostico')),
                ('rutina_sugerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos_que_la_sugirieron', to='gestion.rutina')),
                ('tipo_cabello', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.tipocabello')),
            ],
            options={
                'verbose_name': 'Diagnóstico Capilar',
                'verbose_name_plural': 'Diagnósticos Capilares',
                'ordering': ['-fecha_diagnostico'],
            },
        ),
        migrations.CreateModel(
            name='RequisitoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatorio', models.BooleanField(default=True, help_text='Si es True, el equipo DEBE estar disponible para realizar el servicio')),
                ('cantidad_minima', models.PositiveIntegerField(default=1, help_text='Cantidad mínima de este tipo de equipo necesaria')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_equipamiento', to='gestion.servicio')),
                ('tipo_equipamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_requeridos', to='gestion.tipoequipamiento')),
            ],
            options={
                'verbose_name': 'Requisito de Servicio',
                'verbose_name_plural': 'Requisitos de Servicios',
                'unique_together': {('servicio', 'tipo_equipamiento')},
            },
        ),
    ]
