# Generated by Django 5.2.7 on 2026-01-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_diagnosticocapilar_requisitoservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariolaboral',
            name='fecha_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='fecha_hasta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
