# Generated by Django 5.2.7 on 2026-01-16 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_horariolaboral_fecha_desde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turnos_asignados', to='gestion.personal'),
        ),
    ]
