# Generated by Django 5.2.7 on 2025-12-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_reglacuidado_rutina'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rutinas',
            field=models.ManyToManyField(blank=True, related_name='clientes_guardaron', to='gestion.rutina', verbose_name='Mis Rutinas Guardadas'),
        ),
    ]
