# Generated by Django 5.2.7 on 2026-01-09 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cliente_rutinas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='historial_servicios',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='rutinas',
        ),
    ]
